[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='cea2312d4db4b23921d2f9aea8e8710218acd2bc10f8d71ba1a3edb2f4e61539'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
